language: java
jdk:
  - openjdk7
script: mvn -f converter-core/pom.xml clean initialize clover:instrument-test clover:check clover:clover

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2/
