language: java
jdk:
  - openjdk7

install: true

script: mvn clean initialize clover:instrument-test clover:check clover:clover

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2/
